name: "SolarkCloudV2"
description: "Home Assistant add-on for syncing solar/inverter data from MySolark.com"
version: "2.0.0"
slug: "solark_cloudv2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/Rick-EV/solarkcloudv2/tree/main"
  
  
options:
  solark_user: ""
  solark_pass: ""
  solark_serial: ""
  Home_Assistant_IP: ""
  Home_Assistant_PORT: 8123
  HA_LongLiveToken: ""
  Refresh_rate: 300
  Enable_HTTPS: false
  API_Server: "api.solarkcloud.com"  
  
schema:
  solark_user: str
  solark_pass: password
  solark_serial: str
  Home_Assistant_IP: str
  Home_Assistant_PORT: int
  HA_LongLiveToken: password
  Refresh_rate: int
  Enable_HTTPS: bool
  API_Server: list(api.solarkcloud.com)
